const STORAGE_KEY = 'splitwise-local-ledger-v1';
const SCHEMA_VERSION = 2;
const CATEGORIES = ['Fuel', 'Food', 'Snacks', 'Outing', 'Rent', 'Reimbursement', 'Others'];
const CATEGORY_ICONS = { Fuel: '⛽', Food: '🍴', Snacks: '🍪', Outing: '✦', Rent: '⌂', Reimbursement: '↔', Others: '•' };
const $ = (selector) => document.querySelector(selector);
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const today = () => new Date().toISOString().slice(0, 10);
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const initials = (name) => String(name).split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char]));
const escapeAttr = escapeHtml;
const csvCell = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`;
const defaultPeople = ['You', 'Alex'];
const APP_CONFIG = window.APP_CONFIG || { apiBaseUrl: '' };

function emptyNotebook(name = 'Home', type = 'Home') {
  return { id: uid(), name, type, icon: type === 'Trip' ? '✈' : '⌂', color: '#d9f3e8', currency: 'INR', members: defaultPeople.map((n) => ({ id: uid(), name: n, active: true })), expenses: [], transfers: [], startDate: '', endDate: '', notes: '', archived: false, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() };
}
function normalizeTransaction(transaction, notebook) {
  const byName = new Map(notebook.members.map((member) => [member.name.toLowerCase(), member]));
  const memberFor = (value, fallbackName = '') => { const byId = notebook.members.find((member) => member.id === value); if (byId) return byId; const name = String(fallbackName || value?.name || value || ''); const existing = byName.get(name.toLowerCase()); if (existing) return existing; const member = { id: uid(), name, active: true }; notebook.members.push(member); byName.set(name.toLowerCase(), member); return member; };
  const payer = memberFor(transaction.payerId, transaction.payer);
  const shares = (transaction.shares || []).map((share) => { const member = memberFor(share.personId, share.person); return { personId: member.id, person: member.name, amount: Number(share.amount || 0) }; });
  const category = validCategory(transaction.category) || inferCategory(transaction.description);
  return { ...transaction, id: transaction.id || uid(), kind: transaction.kind === 'transfer' || transaction.kind === 'reimbursement' || category === 'Reimbursement' ? 'transfer' : 'expense', category, payerId: payer.id, payer: payer.name, amount: Number(transaction.amount || 0), shares, date: transaction.date || today() };
}
function migrateState(raw) {
  if (raw?.schemaVersion >= SCHEMA_VERSION && Array.isArray(raw.notebooks)) return raw;
  const legacy = raw || {};
  const notebook = emptyNotebook('Home', 'Home');
  const names = Array.isArray(legacy.people) && legacy.people.length ? legacy.people : defaultPeople;
  notebook.members = names.map((name) => ({ id: uid(), name: String(name), active: true }));
  notebook.expenses = (Array.isArray(legacy.expenses) ? legacy.expenses : []).map((item) => normalizeTransaction(item, notebook)).filter((item) => item.kind === 'expense');
  notebook.transfers = (Array.isArray(legacy.transfers) ? legacy.transfers : []).concat((Array.isArray(legacy.expenses) ? legacy.expenses : []).filter((item) => item.kind === 'transfer' || item.kind === 'reimbursement' || item.category === 'Reimbursement')).map((item) => normalizeTransaction(item, notebook)).filter((item) => item.kind === 'transfer');
  return { schemaVersion: SCHEMA_VERSION, profile: { id: uid(), displayName: 'Local profile', createdAt: new Date().toISOString() }, activeNotebookId: notebook.id, notebooks: [notebook] };
}
function loadState() { try { return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY))); } catch { return migrateState(null); } }
let state = loadState();
let shareType = 'equal'; let editingId = null; let entryMode = 'expense'; let pendingSuggestions = [];
function saveState() { state.schemaVersion = SCHEMA_VERSION; localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function notebook() { return state.notebooks.find((item) => item.id === state.activeNotebookId) || state.notebooks[0]; }
function members(includeInactive = false) { return (notebook()?.members || []).filter((member) => includeInactive || member.active !== false); }
function memberName(id, fallback = '') { return notebook()?.members.find((member) => member.id === id)?.name || fallback; }
function allTransactions() { const book = notebook(); return [...(book?.expenses || []), ...(book?.transfers || [])]; }
function isReimbursement(transaction) { return transaction.kind === 'transfer' || transaction.kind === 'reimbursement' || transaction.category === 'Reimbursement'; }
function findTransaction(id) { return allTransactions().find((item) => item.id === id); }
function validCategory(category) { return CATEGORIES.includes(category) ? category : /reimburs/i.test(String(category || '')) ? 'Reimbursement' : null; }
function inferCategory(description) { const text = String(description || '').toLowerCase(); if (/reimburse|repaid|repay|payback|settle|returned|transfer/.test(text)) return 'Reimbursement'; if (/snack|chips|biscuit|cookie|sweet|dessert|tea|coffee/.test(text)) return 'Snacks'; if (/fuel|petrol|diesel|gas|cng|station/.test(text)) return 'Fuel'; if (/rent|lease|house rent/.test(text)) return 'Rent'; if (/outing|movie|cinema|trip|travel|restaurant|dinner|lunch|breakfast|cafe|party|hotel/.test(text)) return 'Outing'; if (/food|grocery|groceries|vegetable|fruit|milk|bread|rice|meal|swiggy|zomato/.test(text)) return 'Food'; return 'Others'; }
function replaceTransaction(transaction) { const book = notebook(); book.expenses = book.expenses.filter((item) => item.id !== transaction.id); book.transfers = book.transfers.filter((item) => item.id !== transaction.id); (isReimbursement(transaction) ? book.transfers : book.expenses).push(transaction); book.updatedAt = new Date().toISOString(); }

function renderNotebookBar() { const select = $('#notebookSelect'); const visible = state.notebooks.filter((item) => !item.archived); select.innerHTML = visible.map((item) => `<option value="${item.id}" ${item.id === state.activeNotebookId ? 'selected' : ''}>${escapeHtml(item.icon)} ${escapeHtml(item.name)}</option>`).join(''); $('#notebookMeta').textContent = notebook() ? `${notebook().type} · ${notebook().currency}${notebook().archived ? ' · archived' : ''}` : ''; }
function renderPeople() { const book = notebook(); $('#peopleCount').textContent = members().length; $('#peopleList').innerHTML = members(true).map((person) => `<div class="person-row ${person.active === false ? 'inactive' : ''}"><span class="avatar">${initials(person.name)}</span><span>${escapeHtml(person.name)}${person.active === false ? ' · inactive' : ''}</span><button class="remove-person" data-member-action="${person.id}" aria-label="Manage ${escapeAttr(person.name)}">⋯</button></div>`).join(''); const options = members().map((person) => `<option value="${person.id}">${escapeHtml(person.name)}</option>`).join(''); $('#payer').innerHTML = options; $('#transferPayer').innerHTML = options; $('#transferRecipient').innerHTML = options; renderParticipants(); }
function renderCategories() { $('#category').innerHTML = CATEGORIES.filter((category) => category !== 'Reimbursement').map((category) => `<option value="${category}">${category}</option>`).join(''); $('#filterCategory').innerHTML = `<option value="">All categories</option>${CATEGORIES.map((category) => `<option value="${category}">${category}</option>`).join('')}`; }
function renderFilters() { $('#filterMember').innerHTML = `<option value="">All members</option>${members(true).map((person) => `<option value="${person.id}">${escapeHtml(person.name)}</option>`).join('')}`; }
function selectedPeople() { return [...document.querySelectorAll('[data-participant]:checked')].map((input) => input.value); }
function renderParticipants() { const current = selectedPeople(); const selected = current.length ? current : members().map((person) => person.id); $('#participantList').innerHTML = members().map((person) => `<label class="participant-chip ${selected.includes(person.id) ? 'selected' : ''}"><input type="checkbox" data-participant value="${person.id}" ${selected.includes(person.id) ? 'checked' : ''}/>${escapeHtml(person.name)}</label>`).join(''); document.querySelectorAll('[data-participant]').forEach((input) => input.addEventListener('change', () => { input.closest('label').classList.toggle('selected', input.checked); renderShareInputs(); })); renderShareInputs(); }
function renderShareInputs() { const people = selectedPeople(); $('#shareInputs').hidden = shareType === 'equal'; $('#shareInputs').innerHTML = people.map((id) => `<label>${escapeHtml(memberName(id))}<input type="number" min="0" step="${shareType === 'percentage' ? '0.1' : '0.01'}" data-share-value="${id}" placeholder="0" /></label>`).join(''); }
function resetExpenseForm() { editingId = null; $('#expenseForm').reset(); $('#date').value = today(); $('#category').value = 'Others'; shareType = 'equal'; document.querySelectorAll('[data-share]').forEach((button) => button.classList.toggle('active', button.dataset.share === 'equal')); renderParticipants(); document.querySelectorAll('[data-participant]').forEach((input) => { input.checked = true; input.closest('label').classList.add('selected'); }); renderShareInputs(); $('#submitLabel').textContent = 'Add expense'; $('#cancelEditButton').hidden = true; $('#formMessage').textContent = ''; }
function resetTransferForm() { editingId = null; $('#transferForm').reset(); $('#transferDate').value = today(); $('#transferPayer').value = members()[0]?.id || ''; $('#transferRecipient').value = members().find((person) => person.id !== $('#transferPayer').value)?.id || ''; $('#transferSubmitLabel').textContent = 'Add transfer'; $('#cancelTransferEditButton').hidden = true; $('#transferMessage').textContent = ''; }
function setEntryMode(mode) { entryMode = mode; const transfer = mode === 'transfer'; $('#expenseForm').hidden = transfer; $('#transferForm').hidden = !transfer; $('#entryEyebrow').textContent = transfer ? 'BALANCE TRANSFER' : 'NEW EXPENSE'; $('#entryTitle').textContent = transfer ? 'Settle up directly' : 'Log a shared expense'; document.querySelectorAll('[data-entry-mode]').forEach((button) => button.classList.toggle('active', button.dataset.entryMode === mode)); transfer ? resetTransferForm() : resetExpenseForm(); }

function balances() { const result = Object.fromEntries(members(true).map((person) => [person.id, 0])); notebook().expenses.forEach((expense) => { result[expense.payerId] = (result[expense.payerId] || 0) + expense.amount; expense.shares.forEach((share) => { result[share.personId] = (result[share.personId] || 0) - share.amount; }); }); notebook().transfers.forEach((transfer) => { result[transfer.payerId] = (result[transfer.payerId] || 0) + transfer.amount; transfer.shares.forEach((share) => { result[share.personId] = (result[share.personId] || 0) - share.amount; }); }); return result; }
function settlements() { const b = balances(); const debtors = Object.entries(b).filter(([, value]) => value < -0.005).map(([id, value]) => ({ id, value: -value })).sort((a, z) => z.value - a.value); const creditors = Object.entries(b).filter(([, value]) => value > 0.005).map(([id, value]) => ({ id, value })).sort((a, z) => z.value - a.value); const moves = []; debtors.forEach((debtor) => creditors.forEach((creditor) => { if (debtor.value < .005 || creditor.value < .005) return; const amount = Math.min(debtor.value, creditor.value); moves.push({ from: debtor.id, to: creditor.id, amount }); debtor.value -= amount; creditor.value -= amount; })); return moves; }
function filteredTransactions() { const search = $('#searchInput').value.trim().toLowerCase(); const member = $('#filterMember').value; const category = $('#filterCategory').value; const status = $('#filterStatus').value; const b = balances(); return allTransactions().filter((item) => { const text = `${item.description} ${item.category}`.toLowerCase(); const matchesMember = !member || item.payerId === member || item.shares.some((share) => share.personId === member); const matchesStatus = !status || (status === 'unsettled' ? Math.abs(b[item.payerId] || 0) > .005 : Math.abs(b[item.payerId] || 0) <= .005); return (!search || text.includes(search)) && matchesMember && (!category || item.category === category) && matchesStatus; }).sort((a, z) => z.date.localeCompare(a.date)); }
function renderActivity() { const items = filteredTransactions(); $('#activityCount').textContent = items.length; $('#activityList').innerHTML = items.length ? items.map((item) => `<div class="activity-row"><div class="activity-date">${escapeHtml(item.date)}</div><div class="activity-icon category-${item.category.toLowerCase()}">${CATEGORY_ICONS[item.category] || '•'}</div><div class="activity-main"><strong>${escapeHtml(item.description)}</strong><span>${isReimbursement(item) ? 'balance transfer' : `${escapeHtml(memberName(item.payerId, item.payer))} paid · ${escapeHtml(item.category)}`}</span></div><strong class="activity-amount">${money(item.amount)}</strong><div class="activity-actions"><button data-edit-expense="${item.id}">Edit</button><button data-delete-expense="${item.id}">Delete</button></div></div>`).join('') : '<p class="empty-state">No matching activity in this notebook.</p>'; }
function renderDashboard() { renderNotebookBar(); renderFilters(); const total = notebook().expenses.reduce((sum, item) => sum + item.amount, 0); $('#totalTracked').textContent = money(total); $('#expenseCount').textContent = `${notebook().expenses.length} expense${notebook().expenses.length === 1 ? '' : 's'}`; $('#summarySpent').textContent = money(total); $('#summaryExpenses').textContent = notebook().expenses.length; const b = balances(); $('#summaryUnsettled').textContent = money(Object.values(b).filter((value) => value < 0).reduce((sum, value) => sum - value, 0)); const max = Math.max(1, ...Object.values(b).map((value) => Math.abs(value))); $('#balanceList').innerHTML = members(true).map((person) => { const value = b[person.id] || 0; return `<div class="balance-row"><span class="avatar">${initials(person.name)}</span><div><div class="balance-name">${escapeHtml(person.name)}</div><div class="balance-bar"><span style="width:${Math.min(100, Math.abs(value) / max * 100)}%;background:${value >= 0 ? 'var(--accent)' : 'var(--red)'}"></span></div></div><strong class="${value >= 0 ? 'balance-positive' : 'balance-negative'}">${value >= 0 ? '+' : ''}${money(value)}</strong></div>`; }).join(''); $('#settlementList').innerHTML = settlements().length ? `<p class="field-label">Suggested settlements</p>${settlements().map((move) => `<div class="settlement-row"><span>${escapeHtml(memberName(move.from))} → ${escapeHtml(memberName(move.to))}</span><strong>${money(move.amount)}</strong></div>`).join('')}` : '<p class="empty-state">Everyone is settled.</p>'; $('#notebookNotes').textContent = [notebook().startDate && `Dates: ${notebook().startDate} → ${notebook().endDate || 'ongoing'}`, notebook().notes].filter(Boolean).join(' · '); renderActivity(); }

function addExpense(event) { event.preventDefault(); const message = $('#formMessage'); const description = $('#description').value.trim(); const amount = Number($('#amount').value); const payerId = $('#payer').value; const people = selectedPeople(); if (!description || !amount || amount <= 0 || !payerId || !people.length) { message.textContent = 'Add a description, amount, payer, and at least one participant.'; return; } let shares; const values = people.map((id) => ({ id, value: Number(document.querySelector(`[data-share-value="${CSS.escape(id)}"]`)?.value) })); if (shareType === 'equal') { const each = amount / people.length; shares = people.map((personId) => ({ personId, person: memberName(personId), amount: each })); } else if (values.some((entry) => !Number.isFinite(entry.value) || entry.value < 0)) { message.textContent = 'Enter a valid share for every selected person.'; return; } else { const total = values.reduce((sum, entry) => sum + entry.value, 0); const target = shareType === 'percentage' ? 100 : amount; if (Math.abs(total - target) > (shareType === 'percentage' ? .1 : .01)) { message.textContent = `Shares must add up to ${shareType === 'percentage' ? '100%' : money(amount)}.`; return; } shares = values.map(({ id, value }) => ({ personId: id, person: memberName(id), amount: shareType === 'percentage' ? amount * value / 100 : value })); } replaceTransaction({ id: editingId || uid(), kind: 'expense', date: $('#date').value || today(), category: $('#category').value || 'Others', description, amount, payerId, payer: memberName(payerId), splitType: shareType, shares }); saveState(); renderDashboard(); resetExpenseForm(); }
function addTransfer(event) { event.preventDefault(); const amount = Number($('#transferAmount').value); const payerId = $('#transferPayer').value; const recipientId = $('#transferRecipient').value; if (!amount || amount <= 0 || !payerId || !recipientId || payerId === recipientId) { $('#transferMessage').textContent = 'Choose two different people and enter a valid amount.'; return; } replaceTransaction({ id: editingId || uid(), kind: 'transfer', category: 'Reimbursement', date: $('#transferDate').value || today(), description: $('#transferDescription').value.trim() || 'Balance reimbursement', amount, payerId, payer: memberName(payerId), splitType: 'exact', shares: [{ personId: recipientId, person: memberName(recipientId), amount }] }); saveState(); renderDashboard(); resetTransferForm(); }
function editExpense(id) { const item = findTransaction(id); if (!item) return; if (isReimbursement(item)) { setEntryMode('transfer'); editingId = id; $('#transferDescription').value = item.description === 'Balance reimbursement' ? '' : item.description; $('#transferAmount').value = item.amount; $('#transferDate').value = item.date; $('#transferPayer').value = item.payerId; $('#transferRecipient').value = item.shares[0]?.personId || ''; $('#transferSubmitLabel').textContent = 'Update transfer'; $('#cancelTransferEditButton').hidden = false; return; } setEntryMode('expense'); editingId = id; $('#description').value = item.description; $('#amount').value = item.amount; $('#date').value = item.date; $('#payer').value = item.payerId; $('#category').value = item.category; shareType = item.splitType || 'equal'; document.querySelectorAll('[data-share]').forEach((button) => button.classList.toggle('active', button.dataset.share === shareType)); renderParticipants(); document.querySelectorAll('[data-participant]').forEach((input) => { input.checked = item.shares.some((share) => share.personId === input.value); input.closest('label').classList.toggle('selected', input.checked); }); renderShareInputs(); item.shares.forEach((share) => { const input = document.querySelector(`[data-share-value="${CSS.escape(share.personId)}"]`); if (input) input.value = shareType === 'percentage' ? (share.amount / item.amount * 100).toFixed(2) : share.amount.toFixed(2); }); $('#submitLabel').textContent = 'Update expense'; $('#cancelEditButton').hidden = false; }

function renderBulkPreview() {
  $('#bulkPreview').hidden = !pendingSuggestions.length;
  $('#bulkTable').innerHTML = pendingSuggestions.map((item, index) => `<div class="bulk-row" data-bulk-row="${index}"><div class="bulk-row-number">${index + 1}</div><input data-bulk-description value="${escapeAttr(item.description || 'Untitled expense')}" aria-label="Description" /><input data-bulk-amount type="number" min="0.01" step="0.01" value="${item.amount || ''}" aria-label="Amount" /><input data-bulk-date type="date" value="${escapeAttr(item.date || today())}" aria-label="Date" /><select data-bulk-category aria-label="Category">${CATEGORIES.map((category) => `<option value="${category}" ${category === (item.category || 'Others') ? 'selected' : ''}>${category}</option>`).join('')}</select><select data-bulk-payer aria-label="Payer">${members().map((person) => `<option value="${person.id}" ${person.name === item.payer || person.id === item.payerId ? 'selected' : ''}>${escapeHtml(person.name)}</option>`).join('')}</select><input data-bulk-participants value="${escapeAttr((item.participantNames || item.participants || []).map((value) => memberName(value, value)).join(', '))}" aria-label="Participants" /><select data-bulk-split aria-label="Split type"><option value="equal">Equal</option><option value="exact">Exact</option><option value="percentage">Percent</option></select></div>`).join('');
}
function confirmBulk() {
  const added = []; for (const row of [...document.querySelectorAll('[data-bulk-row]')]) { const description = row.querySelector('[data-bulk-description]').value.trim(); const amount = Number(row.querySelector('[data-bulk-amount]').value); const date = row.querySelector('[data-bulk-date]').value || today(); const category = row.querySelector('[data-bulk-category]').value; const payerId = row.querySelector('[data-bulk-payer]').value; const names = row.querySelector('[data-bulk-participants]').value.split(',').map((name) => name.trim()).filter(Boolean); const ids = names.map((name) => members().find((person) => person.id === name || person.name.toLowerCase() === name.toLowerCase())?.id).filter(Boolean); if (!description || amount <= 0 || !ids.length || !payerId) { $('#bulkMessage').textContent = 'Every suggestion needs a description, amount, payer, and known participants.'; return; } const each = amount / ids.length; added.push({ id: uid(), kind: category === 'Reimbursement' ? 'transfer' : 'expense', date, category, description, amount, payerId, payer: memberName(payerId), splitType: 'equal', shares: ids.map((personId) => ({ personId, person: memberName(personId), amount: each })) }); } added.forEach(replaceTransaction); saveState(); pendingSuggestions = []; renderBulkPreview(); $('#bulkText').value = ''; $('#bulkMessage').textContent = `${added.length} transaction${added.length === 1 ? '' : 's'} added to ${notebook().name}.`; renderDashboard();
}

let dialogResolver = null;
let dialogPreviousFocus = null;
function closeAppDialog(value = null) { const dialog = $('#appDialog'); if (!dialogResolver) return; const resolve = dialogResolver; dialogResolver = null; dialog.hidden = true; dialog.setAttribute('aria-hidden', 'true'); dialog.classList.remove('is-danger'); dialogPreviousFocus?.focus?.(); dialogPreviousFocus = null; resolve(value); }
function openAppDialog({ title, message = '', eyebrow = 'ACTION REQUIRED', type = 'confirm', fieldLabel = '', value = '', inputType = 'text', options = [], confirmText = 'Continue', cancelText = 'Cancel', danger = false }) { const dialog = $('#appDialog'); const field = $('#dialogField'); const input = $('#dialogInput'); const select = $('#dialogSelect'); $('#dialogEyebrow').textContent = eyebrow; $('#dialogTitle').textContent = title; $('#dialogMessage').textContent = message; $('#dialogConfirm').textContent = confirmText; $('#dialogCancel').textContent = cancelText; dialog.classList.toggle('is-danger', danger); const hasField = Boolean(fieldLabel); field.hidden = !hasField; input.hidden = !hasField || inputType !== 'text'; select.hidden = !hasField || inputType !== 'select'; $('#dialogFieldLabel').textContent = fieldLabel; input.value = inputType === 'text' ? value : ''; select.innerHTML = options.map((option) => `<option value="${escapeAttr(option.value)}">${escapeHtml(option.label)}</option>`).join(''); if (inputType === 'select') select.value = value; $('#dialogCancel').hidden = type === 'alert'; dialogPreviousFocus = document.activeElement; dialog.hidden = false; dialog.setAttribute('aria-hidden', 'false'); requestAnimationFrame(() => (inputType === 'select' ? select : inputType === 'text' ? input : $('#dialogConfirm')).focus()); return new Promise((resolve) => { dialogResolver = resolve; }); }
$('#dialogForm').addEventListener('submit', (event) => { event.preventDefault(); const input = $('#dialogInput'); const select = $('#dialogSelect'); const value = !$('#dialogField').hidden ? (input.hidden ? select.value : input.value) : true; closeAppDialog(value); }); $('#dialogCancel').addEventListener('click', () => closeAppDialog(null)); $('#dialogClose').addEventListener('click', () => closeAppDialog(null)); document.querySelector('[data-dialog-dismiss]').addEventListener('click', () => closeAppDialog(null)); document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && dialogResolver) closeAppDialog(null); });
async function createNotebook() { const name = await openAppDialog({ title: 'Create a notebook', message: 'Give this shared space a short, recognizable name.', eyebrow: 'NEW NOTEBOOK', fieldLabel: 'Notebook name', value: 'New notebook', confirmText: 'Create notebook' }); if (!name?.trim()) return; const type = await openAppDialog({ title: 'Choose a template', message: 'This helps set the right context for the notebook.', eyebrow: 'NOTEBOOK TEMPLATE', fieldLabel: 'Template', inputType: 'select', value: 'Custom', options: ['Trip', 'Home', 'Friend group', 'Roommates', 'Custom'].map((item) => ({ value: item, label: item })), confirmText: 'Create notebook' }); if (!type) return; const item = emptyNotebook(name.trim(), type); state.notebooks.push(item); state.activeNotebookId = item.id; saveState(); renderPeople(); resetExpenseForm(); renderDashboard(); }
async function manageNotebook() { const book = notebook(); const action = await openAppDialog({ title: `Manage ${book.name}`, message: 'Choose what you would like to do with this notebook.', eyebrow: 'NOTEBOOK SETTINGS', fieldLabel: 'Action', inputType: 'select', value: book.archived ? 'restore' : 'rename', options: [{ value: 'rename', label: 'Rename notebook' }, { value: 'duplicate', label: 'Duplicate notebook' }, { value: 'archive', label: 'Archive notebook' }, { value: 'restore', label: 'Restore notebook' }, { value: 'delete', label: 'Delete notebook' }], confirmText: 'Continue', danger: false }); if (!action) return; if (action === 'rename') { const name = await openAppDialog({ title: 'Rename notebook', message: 'Choose a new name for this notebook.', eyebrow: 'NOTEBOOK SETTINGS', fieldLabel: 'Notebook name', value: book.name, confirmText: 'Save name' }); if (name?.trim()) book.name = name.trim(); } else if (action === 'duplicate') { const copy = structuredClone(book); copy.id = uid(); copy.name = `${book.name} copy`; copy.createdAt = new Date().toISOString(); copy.updatedAt = copy.createdAt; state.notebooks.push(copy); state.activeNotebookId = copy.id; } else if (action === 'archive' && !book.archived) { book.archived = true; state.activeNotebookId = state.notebooks.find((item) => !item.archived && item.id !== book.id)?.id || book.id; } else if (action === 'restore' && book.archived) { book.archived = false; } else if (action === 'delete') { if (state.notebooks.length === 1) { await openAppDialog({ title: 'Notebook cannot be deleted', message: 'Keep at least one notebook so your local ledger always has a home.', eyebrow: 'NOTHING CHANGED', type: 'alert', confirmText: 'Got it' }); return; } const confirmed = await openAppDialog({ title: `Delete ${book.name}?`, message: 'This removes the notebook and all of its expenses and transfers. This cannot be undone.', eyebrow: 'PERMANENT ACTION', confirmText: 'Delete notebook', danger: true }); if (!confirmed) return; state.notebooks = state.notebooks.filter((item) => item.id !== book.id); state.activeNotebookId = state.notebooks.find((item) => !item.archived)?.id || state.notebooks[0].id; } saveState(); renderPeople(); resetExpenseForm(); renderDashboard(); }
function exportCsv() { const lines = [['Record type','Date','Description','Category','Payer','Payee / Person','Split type','Expense amount','Share amount','Balance after all expenses'].map(csvCell).join(',')]; allTransactions().forEach((item) => item.shares.forEach((share) => lines.push([isReimbursement(item) ? 'Reimbursement' : 'Expense', item.date, item.description, item.category, memberName(item.payerId, item.payer), memberName(share.personId, share.person), item.splitType, item.amount.toFixed(2), share.amount.toFixed(2), ''].map(csvCell).join(',')))); Object.entries(balances()).forEach(([id, value]) => lines.push(['Balance','','','','',memberName(id),'','','',value.toFixed(2)].map(csvCell).join(','))); download(`${notebook().name.replace(/\W+/g, '-').toLowerCase()}-export-${today()}.csv`, lines.join('\n'), 'text/csv'); }
function download(filename, content, type) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); }
function exportJson() { download(`splitwise-backup-${today()}.json`, JSON.stringify({ exportedAt: new Date().toISOString(), schemaVersion: SCHEMA_VERSION, profile: state.profile, notebooks: [notebook()] }, null, 2), 'application/json'); }
function importJson(event) { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = async () => { try { const imported = migrateState(JSON.parse(reader.result)); if (!Array.isArray(imported.notebooks) || !imported.notebooks.length) throw new Error('No notebooks found'); imported.notebooks.forEach((item) => { item.id = uid(); item.members = (item.members || []).map((member) => ({ id: uid(), name: member.name || String(member), active: member.active !== false })); item.expenses = (item.expenses || []).map((transaction) => normalizeTransaction(transaction, item)); item.transfers = (item.transfers || []).map((transaction) => normalizeTransaction(transaction, item)); }); state.notebooks.push(...imported.notebooks); state.activeNotebookId = imported.notebooks[0].id; saveState(); renderPeople(); resetExpenseForm(); renderDashboard(); } catch (error) { await openAppDialog({ title: 'Import could not be completed', message: error.message, eyebrow: 'BACKUP ERROR', type: 'alert', confirmText: 'Got it' }); } event.target.value = ''; }; reader.readAsText(file); }

$('#expenseForm').addEventListener('submit', addExpense); $('#transferForm').addEventListener('submit', addTransfer); $('#cancelEditButton').addEventListener('click', resetExpenseForm); $('#cancelTransferEditButton').addEventListener('click', resetTransferForm); $('#exportButton').addEventListener('click', exportCsv); $('#exportJsonButton').addEventListener('click', exportJson); $('#importJsonInput').addEventListener('change', importJson); $('#confirmBulkButton').addEventListener('click', confirmBulk); $('#parseButton').addEventListener('click', async () => { const text = $('#bulkText').value.trim(); if (!text) return $('#bulkMessage').textContent = 'Paste some expense text first.'; $('#parseButton').disabled = true; try { const response = await fetch(`${APP_CONFIG.apiBaseUrl || ''}/api/parse-expenses`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text, people: members().map((person) => person.name) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); pendingSuggestions = (data.expenses || []).map((item) => { const participantNames = item.participants || item.split_with || members().map((person) => person.name); return { ...item, amount: Number(item.amount ?? item.total), payerId: members().find((person) => person.name.toLowerCase() === String(item.payer || item.paid_by || '').toLowerCase())?.id || members()[0]?.id, participantNames }; }); renderBulkPreview(); $('#bulkMessage').textContent = pendingSuggestions.length ? 'Suggestions ready for review.' : 'No complete suggestions found.'; } catch (error) { $('#bulkMessage').textContent = error.message; } finally { $('#parseButton').disabled = false; } });
document.querySelectorAll('[data-entry-mode]').forEach((button) => button.addEventListener('click', () => setEntryMode(button.dataset.entryMode))); document.querySelectorAll('[data-share]').forEach((button) => button.addEventListener('click', () => { shareType = button.dataset.share; document.querySelectorAll('[data-share]').forEach((item) => item.classList.toggle('active', item.dataset.share === shareType)); renderShareInputs(); })); $('#selectAllButton').addEventListener('click', () => { document.querySelectorAll('[data-participant]').forEach((input) => { input.checked = true; input.closest('label').classList.add('selected'); }); renderShareInputs(); }); $('#personForm').addEventListener('submit', async (event) => { event.preventDefault(); const name = $('#personName').value.trim(); if (!name) return; if (members(true).some((person) => person.name.toLowerCase() === name.toLowerCase())) { await openAppDialog({ title: 'That person already exists', message: 'Use a different name to add someone new to this notebook.', eyebrow: 'MEMBER NOT ADDED', type: 'alert', confirmText: 'Got it' }); return; } notebook().members.push({ id: uid(), name, active: true }); saveState(); $('#personName').value = ''; renderPeople(); renderDashboard(); });
$('#notebookSelect').addEventListener('change', (event) => { state.activeNotebookId = event.target.value; pendingSuggestions = []; saveState(); renderPeople(); resetExpenseForm(); renderDashboard(); }); $('#newNotebookButton').addEventListener('click', createNotebook); $('#manageNotebookButton').addEventListener('click', manageNotebook); ['searchInput', 'filterMember', 'filterCategory', 'filterStatus'].forEach((id) => $(`#${id}`).addEventListener('input', renderActivity));
document.addEventListener('click', async (event) => { const edit = event.target.closest('[data-edit-expense]'); if (edit) return editExpense(edit.dataset.editExpense); const del = event.target.closest('[data-delete-expense]'); if (del) { const item = findTransaction(del.dataset.deleteExpense); if (!item) return; const confirmed = await openAppDialog({ title: `Delete ${item.description}?`, message: `This will remove the ${isReimbursement(item) ? 'transfer' : 'expense'} from ${notebook().name}.`, eyebrow: 'PERMANENT ACTION', confirmText: 'Delete', danger: true }); if (confirmed) { notebook().expenses = notebook().expenses.filter((entry) => entry.id !== item.id); notebook().transfers = notebook().transfers.filter((entry) => entry.id !== item.id); saveState(); renderDashboard(); } return; } const memberButton = event.target.closest('[data-member-action]'); if (memberButton) { const member = notebook().members.find((item) => item.id === memberButton.dataset.memberAction); if (!member) return; const action = await openAppDialog({ title: `Manage ${member.name}`, message: 'Choose an action for this notebook member.', eyebrow: 'MEMBER SETTINGS', fieldLabel: 'Action', inputType: 'select', value: 'rename', options: [{ value: 'rename', label: 'Rename member' }, { value: 'inactive', label: 'Mark as inactive' }], confirmText: 'Continue' }); if (action === 'rename') { const name = await openAppDialog({ title: `Rename ${member.name}`, message: 'Choose a name that will be easy to recognize in your ledger.', eyebrow: 'MEMBER SETTINGS', fieldLabel: 'Member name', value: member.name, confirmText: 'Save name' }); if (name?.trim()) member.name = name.trim(); } else if (action === 'inactive') member.active = false; if (action) { saveState(); renderPeople(); renderDashboard(); } } });
renderCategories(); renderPeople(); resetExpenseForm(); resetTransferForm(); renderDashboard(); saveState();
